language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -r ./build/build-requirements.txt
script:
  - make test
  - make setup
  - make install
  # - make package
after_success:
  - make clean
  - pip uninstall -y ppi-sanitize
#   - >
#     if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
#       echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin ;
#       echo "Pushing built Docker Image to: $TRAVIS_REPO_SLUG" ;
#       make ship ;
#     fi ;
#   - "[ -e \"~/.docker/config.json\" ] && shred -n 30 -u -z ~/.docker/config.json"
